# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 16:13
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ums', '0001_initial'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/gabriel/Escriptori/code_submission/static_server/protected'), upload_to='submissions')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.Student')),
            ],
        ),
    ]
