# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
