# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not revised'), (1, 'Started revising'), (2, 'Revised and accepted'), (3, 'Revised and declined')], default=0),
        ),
    ]
