# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20160607_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
