# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_submission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.URLField(),
        ),
    ]
