# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
