# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
